package com.payment.gateway.thirdpart.unionpay.acp.demo;

import java.util.HashMap;
import java.util.Map;

import com.unionpay.acp.sdk.SDKConfig;

/**
 * 
 * Name:  Payment over Internet - Cross-border<br>
 * Function: 5.1.1 Back-end Launch<br>
 * Back-end Transaction<br>
 * Version:  5.0<br>
 * Updated:  July 2014<br>
 * Author:  China UnionPay ACP Team<br>
 * Copyright:  China UnionPay<br>
 * Notes: The following sample code is for testing only. Merchants can write their own code based on their needs following technical documentation. The following code is for reference only.<br>
 */
public class Form00_5_1_1 extends DemoBase {

	public static Map<String, String> setFormDate() {
		/**
		 * Assembly request message
		 */
		Map<String, String> contentData = new HashMap<String, String>();
		// Constant value: 5.0.0
		contentData.put("version", "5.0.0");// M
		// Default value: UTF-8
		contentData.put("encoding", "UTF-8");// M
		// Value: 01 (RSA)
		contentData.put("signMethod", "01");// M
		// Value: 79
		contentData.put("txnType", "79");// M
		// 04: launched in a unified way
		contentData.put("txnSubType", "04");// M
		// 000801:Inter-bank Acquiring
		contentData.put("bizType", "000801");// M
		// 1: Acquirer Access
		contentData.put("accessType", "1");// M
		// Channel type
		contentData.put("channelType", "07");// M
		// Acquirer Code
		contentData.put("acqInsCode", "00010000");
		// Merchant ID
		contentData.put("merId", "802290049000180");// M
		// Merchant Category
		contentData.put("merCatCode", "");// M
		// Merchant Name
		contentData.put("merName", "");// M
		// Merchant Abbreviation
		contentData.put("merAbbr", "");// M
		// Merchant order No., generated by the merchant. Merchant's unique internal number.
		contentData.put("orderId", getOrderId());// M
		// Date and time when merchant sends transaction
		contentData.put("txnTime", getCurrentTime());// M
		// Account
		contentData.put("accNo", "622188123456789");// M
		// Card verification information and ID information
		contentData.put("customerInfo", getCustomer(encoding));// C
		// International area code
		contentData.put("intlAreaCd", "123456");

		return contentData;
	}

	public static void main(String[] args) {

		/**
		 * <pre>
		 * Parameter initialization 
		 * 1. When it runs as a java main method, configuration file will be loaded every time. 
		 * 2. When it runs as a java web application, code for configuration file initialization can be included in listener.
		 * </pre>
		 */
		SDKConfig.getConfig().loadPropertiesFromSrc();// Load acp_sdk.properties from classpath

		/**
		 * Transaction request url, read from configuration file
		 */
		String requestBackUrl = SDKConfig.getConfig().getBackRequestUrl();
		Map<String, String> resmap = submitDate(setFormDate(), requestBackUrl);

		System.out.println(resmap.toString());

	}

}
