package com.payment.gateway.thirdpart.unionpay.acp.demo;

import java.util.HashMap;
import java.util.Map;

import com.unionpay.acp.sdk.SDKConfig;

/**
 * 
 * Name:  Payment over Internet - Cross-border<br>
 * Function: 5.3.2　Purchase Cancellation<br>
 * Back-end Transaction<br>
 * Version:  5.0<br>
 * Updated:  July 2014<br>
 * Author:  China UnionPay ACP Team<br>
 * Copyright:  China UnionPay<br>
 * Notes: The following sample code is for testing only. Merchants can write their own code based on their needs following technical documentation. The following code is for reference only.<br>
 */
public class Form00_5_3_2 extends DemoBase {

	public static Map<String, String> setFormDate() {

		Map<String, String> contentData = new HashMap<String, String>();

		// Constant value
		contentData.put("version", version);// M
		// Default value: UTF-8
		contentData.put("encoding", encoding);// M
		// 01RSA02 MD5 (not supported temporarily)
		contentData.put("signMethod", "01");// M
		// Value: 31
		contentData.put("txnType", "31");// M
		// Default: 00
		contentData.put("txnSubType", "00");// M
		// 000301 Merchant-Hosted
		contentData.put("bizType", "000301");// M
		// Channel type
		contentData.put("channelType", "07");// M
		// Used when back end returns merchant result; if data is submitted, back-end transaction result notice will be sent to merchant.
		contentData.put("backUrl", backUrl);// M
		// 0: Direct access by ordinary merchant; 2: Access by platform merchant
		contentData.put("accessType", "0");// M
		// Acquirer Code
		contentData.put("acqInsCode", "00010000");
		// Merchant ID
		contentData.put("merId", "802290049000180");// M
		// Merchant Category
		contentData.put("merCatCode", "");// M
		// Merchant Name
		contentData.put("merName", "");// M
		// Merchant Abbreviation
		contentData.put("merAbbr", "");// M
		// No. of purchase cancellation, generated by merchant
		contentData.put("orderId", getOrderId());// M
		// Original transaction serial No.. Fill in original transaction queryId
		contentData.put("origQryId", "");// M
		// When order is sent
		contentData.put("txnTime", getCurrentTime());// M
		// Transaction amount, which should be consistent with original transaction amount
		contentData.put("txnAmt", "");// M

		return contentData;
	}

	public static void main(String[] args) {

		/**
		 * <pre>
		 * Parameter initialization 
		 * 1. When it runs as a java main method, configuration file will be loaded every time. 
		 * 2. When it runs as a java web application, code for configuration file initialization can be included in listener.
		 * </pre>
		 */
		SDKConfig.getConfig().loadPropertiesFromSrc();

		/**
		 * Transaction request url, read from configuration file
		 */
		String requestBackUrl = SDKConfig.getConfig().getBackRequestUrl();
		Map<String, String> submitFromData = signData(setFormDate());

		Map<String, String> resmap = submitUrl(submitFromData, requestBackUrl);

		System.out.println(resmap.toString());
	}

}
